### ISSUE TITLE
Quality border of items

### ISSUE THREAD

**Issue by dutrieux** [Nevcairiel/Inventorian#1]
I will be nice if we could have a quality border of items like :  https://www.wowinterface.com/downloads/info7142-oGlow.html

Thx for your work

Duto

**Comment by Nevcairiel** [comment]
This is already a feature available in Inventorian, it was quite simply broken in Classic, but was fixed in fc50d04e

**Comment by Steffen-Hadberg-Nielsen** [comment]
https://www.curseforge.com/wow/addons/inventorian/files
Latest version on curseforge doesn't have the issue fixed and when downloading from github the one bag feature doesnt work but item quality border does

**Comment by dutrieux** [comment]
There is a **CI problem** with your https://github.com/Nevcairiel/Inventorian/commit/fc50d04ea7976608e98347676728e71386febc26 commit :s

**Comment by Nevcairiel** [comment]
But that doesn't matter because it was fixed in the following commit, which is also available as an alpha version on wowace.
