### ISSUE TITLE
Quest item on classic

### ISSUE THREAD

**Issue by Paroyer** [Nevcairiel/Inventorian#11]
An option or what not to give a special color to quest item could be awesome, only little thing that keeps me on Bagnon even tho i really prefer your UI. I dont know how they done this but with Bagnon quest item are bright yellow. Oh and also just cause I talk about bagnon it's not much important but a slider for item glow intensity could be even more awesome, i know it's not everyone that necesserly like the same glow.

**Comment by Nevcairiel** [comment]
I've just added very rudimentary quest item detection for items actually marked as quest items by the game

**Comment by Paroyer** [comment]
Yeah that's perfect with this brother!

**Comment by Twizt3r** [comment]
Sorry to talk on such on old post. But can this feature be optional ? The golden glow inside the item isn't only on actual quest items, it's also on "keys", like Maraudon Scepter and Zull'Farrak Mallet. And on other items like the Blacksmithing trinket.
