### ISSUE TITLE
Vulpera Alpaca Saddlebags BUG.

### ISSUE THREAD

**Issue by zkpjy** [Nevcairiel/Inventorian#18]
If Vulpera then [Alpaca Saddlebags] It will cause offline backpacking and display spaces
![aa](https://user-images.githubusercontent.com/73094509/160387400-a2e86272-48de-4a30-85af-4e7decf9d23d.jpg)
.

**Comment by Nevcairiel** [comment]
This should be fixed. Might need to login the Vulpera once to update the cache.
