### ISSUE TITLE
ElvUI compatibility - All bag slots show quest exclamation mark

### ISSUE THREAD

**Issue by AbstractionByDesign** [Nevcairiel/Inventorian#23]
When using Inventorian with elvui (bags module disabled), all bag slots display the quest item texture.

![image](https://user-images.githubusercontent.com/26334183/192136402-a82ea1e3-3677-474d-9dcd-f85e7e9fc6fc.png)

**Comment by AbstractionByDesign** [comment]
I've deleted the Exclamation mark in the texture file BagQuestItem.tga using paint.net.

This acts a temp fix for anyone with a similar problem and doesn't care about quest icons.

**Comment by Nevcairiel** [comment]
Inventorian uses the official Blizzard API to identify quest items. I have no idea what ElvUI does to make them show up even on empty slots.

**Comment by Romsh** [comment]
I contacted ElvUI team via Discord and someone asked me to try to disabling "Blizzard skin for bags".  ("Sacs" in French, bottom left)
Seems like this is the thing that cause this weird bug.
![image](https://user-images.githubusercontent.com/25463148/192245312-56b46cde-e326-42aa-890d-99d5779f09a8.png)

For me it seems like the "Activate/Disable ElvUI bags" that doesn't work properly but it's just my guess.
I hope it helped.

**Comment by Nevcairiel** [comment]
This might be fixed in the latest update.
